import { CHORUS_MEMORY_SERVER } from '../services/memoryService'

/**
 * The memory usage contract: what Chorus tells an agent about this project's
 * graph at launch (D148, Task 6a-1).
 *
 * ⚠ PURE, AND DELIBERATELY SO. No `fs`, no `electron`, no `neo4j-driver`, and
 * no adapter imported. It lives here beside `mcpConfigCore.ts` for the same
 * reason that module exists: two adapters need the same rule and a rule with
 * two homes drifts. Both of this module's consumers are adapters and the ipc
 * composition, which is why it is not in `services/`.
 *
 * ⚠ THE PHASE 6 G2 DRIVE IS WHY THIS EXISTS AT ALL. A complete working memory
 * path was proven end to end — and `memory:validate` still returned `0 of 0`,
 * because nothing anywhere had told either agent the graph was there. The
 * provisioner is convenience; this is the gap (D147(b)).
 */

/**
 * ⚠ THE SERVER NAME IS IMPORTED, NEVER RE-TYPED. `memoryService.ts` already
 * records that renaming it would strand the old entry in every `.mcp.json`
 * Chorus has written; a second spelling HERE would be worse in a quieter way —
 * it would teach every agent a name that the config it is reading does not use.
 * The import is type-free and cheap: `memoryService.ts` pulls in no Electron.
 */
export function memoryContractLines(): readonly string[] {
  return [
    `This project has a memory graph, reachable through the "${CHORUS_MEMORY_SERVER}" MCP server (Neo4j, queried with Cypher).`,
    'READ BEFORE ASSUMING: before re-deriving how this project is arranged, or re-discovering a decision, query the graph. Structural nodes (:File, :Directory, :Commit) record where code lives; :Memory nodes record decisions, observations and risks.',
    'WRITE AFTER A MILESTONE, not after every turn: a decision taken, a durable observation, or a risk found — never a running commentary, and never something you have not verified.',
    'EVERY MEMORY MUST CITE ITS SOURCE: attach SUPPORTED_BY to the :File or :Commit it is about, and PRODUCED from your own :AgentSession node. An uncited memory is counted as unsourced and lowers this project’s provenance ratio.',
    'NEVER DELETE OR RELABEL A MEMORY YOU DID NOT WRITE. Supersede instead: set validTo on the old node and create the new one.',
    'Structural nodes are machine-generated by Chorus and are refreshed wholesale; do not hand-edit them.',
    'The graph is scoped to this project. Do not assume it holds anything about another repository.'
  ]
}

/**
 * ⚠ EVERY LINE IS PAID FOR ON EVERY LAUNCH, IN CONTEXT — which is the named
 * cost D147(e) accepted rather than hid, and the reason there are seven lines
 * and not twenty. Each one either prevents a wrong action (writing without a
 * source, deleting someone else's memory, hand-editing generated nodes) or
 * enables a right one (query first). The provenance line in particular exists
 * because `memory:validate`'s denominator would otherwise be measuring
 * compliance with an instruction nobody was ever given.
 *
 * ⚠ EACH ELEMENT IS ONE PHYSICAL LINE AND CONTAINS NO NEWLINE. That is what
 * makes the codex render legal at all — see `assertSingleLine`.
 */

/** claude's file: Markdown, headed, trailing newline. */
export function renderInstructionsMarkdown(lines: readonly string[]): string {
  return ['# Project memory (Chorus)', '', ...lines.map((l) => `- ${l}`), ''].join('\n')
}

/** codex's argv: ONE physical line. */
export function renderInstructionsOneLine(lines: readonly string[]): string {
  return assertSingleLine(lines.join(' '))
}

/**
 * ⚠ LOAD-BEARING, NOT DEFENSIVE — AND THE FAILURE IT PREVENTS IS SILENT.
 * `tomlBasicString` (mcpConfigCore.ts) escapes backslashes and quotes and NOT
 * newlines, so a raw newline reaching a `-c key="…"` override is an illegal
 * TOML basic string — and codex reports an unknown or malformed `-c` path by
 * IGNORING IT WITHOUT A WORD (codex.ts). The symptom would not be an error; it
 * would be a contract that simply never arrives, indistinguishable from an
 * agent that read it and ignored it.
 */
export function assertSingleLine(v: string): string {
  if (/[\r\n]/.test(v)) throw new Error('A codex developer instruction must be one physical line.')
  return v
}
