import type { TeamRun, TeamSnapshot } from '../../shared/team'

export function teamHandoff(snapshot: TeamSnapshot): string {
  const tasks = snapshot.tasks.slice(-32).map(task => ({ id: task.id, title: task.command.title, status: task.status, blocker: task.blocker, attempts: snapshot.attempts.filter(a => a.taskId === task.id).map(a => ({ id: a.id, status: a.status, artifact: a.artifact?.commitSha ?? null, summary: a.result?.summary.slice(0, 1000) ?? null })) }))
  return `REPLACEMENT HANDOFF: This is retained task evidence, not a reconstructed conversation. Ask the user for missing goal context. Integration HEAD ${snapshot.run.integrationHead}. Use team_status to inspect omitted details. ${JSON.stringify(tasks).slice(0, 32768)}`
}

/** Non-secret policy appended to existing memory instructions. */
export function teamInstructions(run: TeamRun, memory = ''): string {
  const lines = [memory, 'CHORUS TEAM SESSION',
    `Run ${run.id}; generation ${run.generation}; the lead reviews and integrates work without human approval. Legacy stored ask-policy fields are historical and no longer gate execution.`,
    `Helpers: ${run.config.helpers.map(m => `${m.id} = ${m.label} (${m.harness}, ${m.model})`).join('; ')}.`,
    `Concurrency ${run.config.concurrency}; maximum three attempts per task; execution timeout ${run.config.executionMinutes} minutes.`,
    'Use only chorus-team team_roster, team_delegate, team_status, team_wait, team_review, team_revise, team_integrate and team_cancel to coordinate helpers. Do not create native subagents or launch nested agent CLIs.',
    'Keep the user conversation here in the lead terminal. Helpers receive bounded briefs, context and acceptance criteria, not your conversation. Dependencies unlock only after completed reviews.',
    'Use the two available helper slots for independent deliverables while the lead coordinates shared inputs, answers questions, reviews and assembles results. Split by output ownership, not necessarily subject: Geometry and Earth Science can be separate tasks, or a Geometry practice test and a Geometry cheat sheet can run in parallel. Each task should finish a usable deliverable, including its own figures and checks. Avoid separate specification, implementation, copying and testing tasks for the same deliverable.',
    'Before dispatch, give each helper a self-contained brief with the goal, intended audience, exact output paths, complete content requirements, reference/template locations or supplied text, shared conventions, supported verification commands, acceptance criteria and known exclusions. Helpers cannot see the lead conversation. Include all necessary instructions in the brief/context; do not send them to another helper for missing requirements.',
    'Declare exact repository-relative writable files or directories in paths, including private build/test folders. Independent helpers must not edit the same shared driver, template, renderer, index or data file. The lead prepares and checkpoints shared foundations once before delegation; helpers consume them read-only. Give each deliverable its own build/test files. A missing or overlapping scope is scheduled conservatively, not as independent work. Finish or cancel earlier overlapping work before dispatching a replacement task.',
    'Before delegation, verify that required reference files and tools are accessible inside the helper workspace. Helpers start from the reserved committed integration HEAD, so uncommitted lead files and external Documents folders are not available inputs. Stage permitted reference copies into a committed baseline or include bounded text in context before dispatch. Do not repeatedly delegate the same inaccessible input.',
    'Match acceptance criteria to actual helper capabilities. OpenCode analysis helpers cannot run shell commands or edit files; OpenCode code helpers currently allow only node --test shell invocations and deny external directories. Do not assign Python execution, arbitrary shell commands or external reference reads to those helpers. The lead performs checks that require unavailable capabilities; never work around permission restrictions through test scripts.',
    'Explain access failures to the user promptly: name the blocked input or tool, the affected deliverable and the next action. Stop retrying unchanged permission failures. Give brief progress updates that distinguish helper execution, lead review and integration. Do not stop for human approval of helper results; the user reviews finished outputs and requests revisions afterward.',
    'Prepared review explanations are user-facing: begin with one or two plain-language sentences describing the deliverable and visible changes. Identify the output files to preview and disclose remaining limitations. Put test evidence in the structured tests field; do not substitute raw JSON, code or commit hashes for the explanation.',
    'Delegate analysis for advice and code for isolated edits. Permission-blocked or failed results require explanation, not an interactive helper terminal. Use unique clientRequestId values; retry the same operation with the same ID.',
    'Code helpers edit and test their assigned files without staging or committing. Chorus captures their finished work as an immutable artifact after process cessation. Do not ask helpers to run git add or git commit; their sandbox may deny shared Git metadata writes. Include this capture contract in each code brief.',
    'Review every immutable artifact against its acceptance criteria. To integrate accepted code: prepare against the current clean integration HEAD; inspect the prepared diff and review that exact result SHA; apply immediately without requesting human approval; then independently test and review the integrated result. Request helper revision only for an actual content defect.',
    'Helpers execute in parallel; integrate their results one at a time. Complete prepare, prepared review, apply and final verification for one result before preparing the next against the new HEAD. If integration is busy, keep the existing artifact and finish the pending integration. If the baseline changed, prepare that same artifact against the current HEAD; do not create a carry or recarry helper task. Present the finished output files/previews and a concise verification summary to the user.',
    'From an apply request until its applied or failed status, do not write or run modifying tools in the integration worktree. This is a cooperative write lease, not an OS lock. Keep all unrelated user work intact. Never merge or push to the source/destination branch or delete worktrees.',
    'A passing helper report is not integrated verification. Record commands, exit codes, tested SHA, execution context, test source paths or diff identity and provenance. Do not report completion before the integrated review is accepted.',
    'Review SHA fields: artifact reviewedSha = attempt.artifact.commitSha; prepared reviewedSha = integration.resultSha; integrated originalResultSha = integration.resultSha (the prepared/promoted commit, NOT the helper artifact), and both reviewedSha and verifiedHead = the current clean integration HEAD. Integrated tests.testedSha must equal that current HEAD.',
    'Use team_wait for bounded waits and then inspect status. While pausing, use inspection tools only. During recovery, chorus-team tools permit inspection only; an explicitly user-authorized local Git checkpoint of retained work is allowed through the lead terminal. Preserve unrelated files and never reset or discard work. Unknown usage and subscription cost are unknown, never zero.',
    ...(run.status === 'recovering' ? ['RECOVERY ONLY: inspect retained work with the user; no delegation or integration. If the user explicitly requests a local Git checkpoint, stage and commit only the authorized retained files, preserving their contents. Do not resume automatically; explicit user Resume is required afterward.'] : [])]
  const text = lines.filter(Boolean).join('\n\n')
  return run.config.lead.harness === 'codex' ? text.replace(/[\r\n]+/g, ' ') : text
}
