import { focusedTeamClaudeVersion, decisionWaitCodexVersion } from '../../shared/team'
import type { TeamRun, TeamSnapshot } from '../../shared/team'

export function teamHandoff(snapshot: TeamSnapshot): string {
  const tasks = snapshot.tasks.slice(-32).map(task => ({ id: task.id, title: task.command.title, status: task.status, blocker: task.blocker, attempts: snapshot.attempts.filter(a => a.taskId === task.id).map(a => ({ id: a.id, status: a.status, artifact: a.artifact?.commitSha ?? null, summary: a.result?.summary.slice(0, 1000) ?? null })) }))
  return `REPLACEMENT HANDOFF: This is retained task evidence, not a reconstructed conversation. Ask the user for missing goal context. Integration HEAD ${snapshot.run.integrationHead}. Use team_status to inspect omitted details. ${JSON.stringify(tasks).slice(0, 32768)}`
}

/** Non-secret policy appended to existing memory instructions. */
export function teamInstructions(run: TeamRun, memory = ''): string {
  const waitTimeout = (run.config.lead.harness === 'claude' && focusedTeamClaudeVersion(run.config.lead.installedVersion)) || (run.config.lead.harness === 'codex' && decisionWaitCodexVersion(run.config.lead.installedVersion)) ? 900000 : 20000
  const lines = [memory, 'CHORUS TEAM SESSION',
    `Run ${run.id}; generation ${run.generation}; the lead reviews and integrates work without human approval. Legacy stored ask-policy fields are historical and no longer gate execution.`,
    `Helpers: ${run.config.helpers.map(m => `${m.id} = ${m.label} (${m.harness}, ${m.model})`).join('; ')}.`,
    `Concurrency ${run.config.concurrency}; maximum three attempts per task; execution timeout ${run.config.executionMinutes} minutes.`,
    'Coordinate only through chorus-team tools. Do not create native subagents or launch nested agent CLIs. team_status and team_wait return compact task records; lastSequence is an actionable cursor. Reuse it in waits. Read full evidence or paginated diffs with team_detail only when needed; follow pagination before concluding review.',
    'Keep the user conversation here in the lead terminal. Helpers receive bounded briefs, context and acceptance criteria, not your conversation. Dependencies unlock only after completed reviews.',
    'Use the two available helper slots for independent deliverables while the lead coordinates shared inputs, answers questions, reviews and assembles results. Split by output ownership, not necessarily subject: Geometry and Earth Science can be separate tasks, or a Geometry practice test and a Geometry cheat sheet can run in parallel. Each task should finish a usable deliverable, including its own figures and checks. Avoid separate specification, implementation, copying and testing tasks for the same deliverable.',
    'Before dispatch, give each helper a concise assignment: goal, intended audience, output ownership, relevant specification sections, additional constraints and acceptance criteria. Declare committed specification/test/template files in references; these supply the detailed requirements. Do not copy an existing specification into brief/context. Aim for at most 2000 characters of brief/context when references exist. Helpers cannot see your conversation, but Chorus instructs them to read the referenced contracts before implementing. For tasks without committed contracts, include the necessary bounded requirements inline. Chorus supplies sandbox/check/capture rules; do not repeat them in every brief.',
    'Declare exact repository-relative writable files or directories in paths, including private build/test folders. Independent helpers must not edit the same shared driver, template, renderer, index or data file. The lead prepares and checkpoints shared foundations once before delegation; helpers consume them read-only. Give each deliverable its own build/test files. A missing or overlapping scope is scheduled conservatively, not as independent work. Finish or cancel earlier overlapping work before dispatching a replacement task.',
    'Before delegation, verify that required reference files and tools are accessible inside the helper workspace. Helpers start from the reserved committed integration HEAD, so uncommitted lead files and external Documents folders are not available inputs. Stage permitted reference copies into a committed baseline or include bounded text in context before dispatch. Do not repeatedly delegate the same inaccessible input.',
    `Match acceptance criteria to actual helper capabilities. OpenCode analysis helpers cannot run shell commands or edit files. Code helpers allow standalone ${run.config.verificationProfile === 'npm-project' ? 'node --test, npm test, npm run typecheck and npm run build' : 'node --test'} commands, without extra arguments or compound shell commands, and deny external directories. Declare reference paths in references so Chorus can preflight committed availability. Do not assign unsupported commands; never work around permission restrictions through test scripts.`,
    'Explain access failures to the user promptly: name the blocked input or tool, the affected deliverable and the next action. Stop retrying unchanged permission failures. Give brief progress updates that distinguish helper execution, lead review and integration. Do not stop for human approval of helper results; the user reviews finished outputs and requests revisions afterward.',
    'Prepared review explanations are user-facing: begin with one or two plain-language sentences describing the deliverable and visible changes. Identify the output files to preview and disclose remaining limitations. Artifact/prepared reviews normally omit tests and verificationIds; helper-reported checks are not independent evidence. For integrated reviews submit verificationIds, never copy check logs or proof fields into tests. Do not substitute raw JSON, code or commit hashes for the explanation.',
    'Delegate analysis for advice and code for isolated edits. Permission-blocked or failed results require explanation, not an interactive helper terminal. Use unique clientRequestId values; retry the same operation with the same ID.',
    'Code helpers edit and test their assigned files without staging or committing. Chorus supplies their capture contract and captures finished work as an immutable artifact after process cessation. Do not ask helpers to run git add or git commit; their sandbox may deny shared Git metadata writes.',
    'Review every immutable artifact against its acceptance criteria. To integrate accepted code: prepare against the current clean integration HEAD; inspect the prepared diff and review that exact result SHA; apply immediately without requesting human approval; then independently test and review the integrated result. Request helper revision only for an actual content defect.',
    'Helpers execute in parallel; prepare, review and apply their results one at a time against the new HEAD. Independent results may all be applied before the shared full suite runs. Then independently test the final combined HEAD and complete each integrated review using that current verified HEAD and its originalResultSha. If integration is busy, keep the existing artifact and finish the pending integration. If the baseline changed, prepare that same artifact against the current HEAD; do not create a carry or recarry helper task. Present finished outputs and a concise verification summary.',
    'From an apply or verification request until its completed/failed status, do not write or run modifying tools in the integration worktree. This is a cooperative write lease, not an OS lock. Keep unrelated user work intact. Never directly merge, push or delete worktrees; Chorus owns these effects through team_finish.',
    'A passing helper report is not integrated verification. Chorus records commands, exit codes, tested SHA, execution context, test source paths or diff identity and provenance. Reference its completed verification IDs instead of copying evidence. Do not report completion before the integrated review is accepted.',
    ...(run.config.verificationProfile ? ['Use team_verify command suite at the exact current integration SHA for independent checks. It returns verificationIds; wait with target checks and those IDs. Completed compact summaries contain outcome, exit code and tested SHA. Submit the same verificationIds for each integrated review of that final HEAD, using team_review_many when several results are ready. Inspect team_detail section checks only when you need full logs. Do not invent evidence or echo logs. After all reviews complete, call team_finish with the clean current integration SHA. It reuses valid final-HEAD checks and records publication/cleanup in the Team panel. Do not repeatedly poll finish; Chorus owns final checks, publication, lead retirement and cleanup. Do not edit during finish.'] : []),
    'Stop unchanged permission failures. One automatic content revision is enough; after that explain the defect and repair it as lead or ask for direction. Keep implementation with helpers and architecture/review with the lead. Small changes may be faster without delegation; do not split a single deliverable into copying or recarry tasks.',
    'Review SHA fields: artifact reviewedSha = attempt.artifact.commitSha; prepared reviewedSha = integration.resultSha; integrated originalResultSha = integration.resultSha (the prepared/promoted commit, NOT the helper artifact), and both reviewedSha and verifiedHead = the current clean integration HEAD. Integrated tests.testedSha must equal that current HEAD.',
    `Use team_delegate_many for independent assignments and team_review_many for same-phase reviews. Preparation/application remain serial against exact HEADs; inspect every paginated diff before acceptance. When no other lead work is pending, use team_wait target results with outstanding taskIds, target checks with verificationIds, or target finish; choose timeoutMs ${waitTimeout}. Decision waits suppress routine internal progress and hold one tool call open without model polling. Reuse lastSequence for results so already-reviewed outcomes do not wake the next wait. Responses include current state; do not follow every wait with team_status. While pausing, use inspection tools only. During recovery, chorus-team tools permit inspection only; an explicitly user-authorized local Git checkpoint of retained work is allowed through the lead terminal. Preserve unrelated files and never reset or discard work. Unknown usage and subscription cost are unknown, never zero.`,
    ...(run.status === 'recovering' ? ['RECOVERY ONLY: inspect retained work with the user; no delegation or integration. If the user explicitly requests a local Git checkpoint, stage and commit only the authorized retained files, preserving their contents. Do not resume automatically; explicit user Resume is required afterward.'] : [])]
  const text = lines.filter(Boolean).join('\n\n')
  return run.config.lead.harness === 'codex' ? text.replace(/[\r\n]+/g, ' ') : text
}
